# This is a basic workflow to help you get started with Actions

name: meal-bot

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with: 
          python-version: 3.8
      - name: Create dot env file
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv
          pip install line-bot-sdk
      - name: Create dot env file
        run: |
          touch .env
          echo "CHANNEL_ACCESS_TOKEN=${{ secrets.CHANNEL_ACCESS_TOKEN }}" >> .env
          echo "USER_ID=${{ secrets.USER_ID }}" >> .env
      - name: Run script
        run: |
          python message.py
